### PR TITLE
Make simulations design consistent with rest of the site 

### PR DESCRIPTION
**Pull request by ryaanahmed**
This PR adds the panel design pattern to simulations, and moves things around a bit for compactness and ease of use.

@equationcrunchor  --  let me know what you think.

Annotation 2019-05-15 152248

### CODE REVIEW

**Comment by mscuthbert** [comment]
I like a lot better!  General memory can probably have less space between the lines and probably even less padding since it's less important.  

I'm thinking that for the accumulator and storage register, giving the decimal or octal code for the value also might be useful.  (hexadecimal wasn't used nearly as much as octal at the time).

**Comment by ryaanahmed** [comment]
> I like a lot better! General memory can probably have less space between the lines and probably even less padding since it's less important.

Great. Will fix spacing. Padding is mostly because we have an awkward amount of stuff and I couldn't think of a better layout... doesn't make sense to stretch the code box out further. The layout isn't _quite_ there, I think, but good enough for now.


> I'm thinking that for the accumulator and storage register, giving the decimal or octal code for the value also might be useful. (hexadecimal wasn't used nearly as much as octal at the time).

Will make an issue and leave this for later improvement.

**Comment by ryaanahmed** [comment]
Thanks. I'm going to merge and make a tracking issue for these improvements.

**Comment by equationcrunchor** [comment]
Alright, thanks!

**Pull request merged**
