### PR TITLE
Project refactor

### PR DESCRIPTION
**Pull request by ryaanahmed**
This is a major PR, refactoring the whole project. I'm putting this in as a draft PR right now, as bits and pieces still need finishing, but the bones are there, and I wanted to open this up for team feedback before I finish it up.

Big changes:

0. The top level now separates code from data from documentation/writeups/other misc. text files that aren't part of the running of the system.

1. the `code` dir reorganizes all of the running code into two Django apps `archives` (formerly `dj_comp_hist`), `simulations` (pretty much untouched) and a `utilities` dir (not a Django app!) containing misc code called from various parts of the system. `utilities` contains a lot of stuff that was formerly spread out in various places.

Updating and running should be (fingers crossed) straightforward: the whole workflow up through running populate_from_metadata and actually running the site should work. Some of the OCR stuff still needs updating to the new file paths before it'll work correctly.

Please let me know if this general structure looks good, or if anything wants restructuring. It should be a little easier to get around the project now.

Since the top level is not part of the actual Python project, you'll need to let PyCharm know that `code` is the source root by right clicking the directory > 'Mark Directory As' > 'Source Root'.

### CODE REVIEW

**Comment by mscuthbert** [comment]
What would happen if we moved the three folders of code to the top level directory until the end of the term?  It would be messier for data encapsulation and not a format we want to go through for future projects (and might warrant a second refactor in June), but I ask because anything that requires a reconfiguration of PyCharm for the students will take at least a week to propagate, since it's not something we can just push out to them, and for some students still (even some of the top programmers), finding their source directory on their HDs is something that needs staff guidance.

**Comment by mscuthbert** [comment]
If we stick with this setup, it might still be better to rename "code" to "dj_web" or something like that since this is a directory that the students are familiar with cd'ing into and locating.

**Comment by ryaanahmed** [comment]
> What would happen if we moved the three folders of code to the top level directory until the end of the term?

I think that's totally fine. Like you say, less than ideal to mix code and data, but it's not a huge deal. I think the wins in terms of folks being less confused (and PyCharm assuming that the top level directory is the source root by default) are probably worth it.

**Comment by srisi** [comment]
Generally looks good to me.
computation_hist and djweb folder are still going to get deleted, correct?
What's a bit confusing right now is the combination of specifically django and non-django directories at the top level, i.e. is config a project config or a django config? One way of making that explicit would be to rename to dj_apps, dj_config, and dj_templates and leave the other folders as is. That way they would at least be grouped together when looking at the directory. Though I don't know if this messes up other configurations.

Minor suggestions:
- delete base.html (I don't think it gets used)
- move MIT Campus Map.html to z_unused (created by student who is no longer in the lab)
- apply filters while processing search (probably didn't make it over from master)

**Comment by ryaanahmed** [comment]
> computation_hist and djweb folder are still going to get deleted, correct?

Yeah, they're gone and distributed throughout the new project structure.


> One way of making that explicit would be to rename to dj_apps, dj_config, and dj_templates and leave the other folders as is.

Good idea. Not a problem for the settings (just need to rename the references).

I'm going to do that right now—once I commit, if you or Lisa have a spare moment, could you try pulling this branch and setting up / running from it? I want to make sure to troubleshoot the process with you guys, in case there are any problems out of my refactor, since I won't physically be in the lab next week to help any students who have problems. (This is not urgent, but we should do it on Monday 4/1 at the latest.)

**Comment by ryaanahmed** [comment]
> apply filters while processing search (probably didn't make it over from master)

GAH. Apparently I have some kind of mental block around this.

**Comment by ryaanahmed** [comment]
> One way of making that explicit would be to rename to dj_apps, dj_config, and dj_templates and leave the other folders as is.

Actually, I've done this, and now I'm having second thoughts. The reason is this:

> i.e. is config a project config or a django config

The idea here is that there's no distinction anymore between these things. Everything is part of one system. That boundary was pretty artificial to begin with, as code in the "non-Django" part of the system was often calling code in the Django part of the system.

I'd advocate for leaving the names `apps`, `config`, `templates` without any `dj_` prefix. I also don't feel very strongly about this. I'd suggest we do whatever seems like it will be least confusing for everyone next week and am happy to defer to other opinions.

**Comment by srisi** [comment]
> I'd advocate for leaving the names `apps`, `config`, `templates` without any `dj_` prefix. I also don't feel very strongly about this. I'd suggest we do whatever seems like it will be least confusing for everyone next week and am happy to defer to other opinions.

I don't have very strong feelings about this either. One less orthodox option might be to move the contents of config and templates (i.e. settings.py, urls.py, wsgi.py, and base.jinja2) into the apps folder. Definitely not optimal as the app grows but it could be convenient for now. (the idea comes partially from looking for the base.jinja2 more times than I care to admit)

**Comment by srisi** [comment]
Things seem to work well. I deleted my db and ran migrations, populate, runserver. All seems to work. 
The main issue I have is that when I change to the refactor branch, the files that are not under version control (e.g. the db.sqlite in djweb) still remain. Hence, the computation_hist and djweb folders remain on my machine, which is confusing. I guess the solution is to remove those files from gitignore.
Screenshot 2019-03-27 16 19 05

**Comment by ryaanahmed** [comment]
> One less orthodox option might be to move the contents of config and templates (i.e. settings.py, urls.py, wsgi.py, and base.jinja2) into the apps folder. 

As you suggest, this is not a good idea for future maintenance. Better to keep these things where they are.

> The main issue I have is that when I change to the refactor branch, the files that are not under version control (e.g. the db.sqlite in djweb) still remain. Hence, the computation_hist and djweb folders remain on my machine, which is confusing. I guess the solution is to remove those files from gitignore.

Ah, yeah, these directories are going to have all of the stuff that we gitignore, including pycache, the db, etc. We don't want to remove these from gitignore,  though—the trouble is they're untracked on every individual machine, so doing that won't let us remove them at the point of merge, and then we'll have a mess on our hands afterwards. We want everyone to delete the old versions locally. (Although it's not really a big deal if they stick around on a local machine... they'll be completely unused by the system.)

`git clean` removes untracked files. Giving it the `-x` flag removes ignored and unadded files, and `-d` removes untracked directories. `-n` for a dry run, then `-f` to force delete.

So, from the project root directory: `git clean -dx -n` to see what it wants to delete, and then `git clean -dx -f` to actually delete them, which should give a working directory that exactly matches the repo.

**Comment by srisi** [comment]
> `git clean` removes untracked files. Giving it the `-x` flag removes ignored and unadded files, and `-d` removes untracked directories. `-n` for a dry run, then `-f` to force delete.
> 
> So, from the project root directory: `git clean -dx -n` to see what it wants to delete, and then `git clean -dx -f` to actually delete them, which should give a working directory that exactly matches the repo.

Thanks. Can you figure out a way of doing this with Github Desktop? Many/most of our Windows users don't have a working git command line interface.

**Comment by ryaanahmed** [comment]
> Can you figure out a way of doing this with Github Desktop? Many/most of our Windows users don't have a working git command line interface.

There doesn't seem to be a way. GitHub Desktop doesn't have any management of untracked files baked in. I'd say this isn't a big deal—we can instruct students to manually delete these two folders, which should only contain build (by)products like `db.sqlite3` and `__pycache__`. There's really no way around this other than not doing the refactor at all (which would be a bad idea for future maintenance)!

**Pull request merged**
