### PR TITLE
adds full text search to keyword search

### PR DESCRIPTION
**Pull request by ryaanahmed**
I am _not_ sure about this. On the one hand, it improves the search feature tremendously.

On the other hand, it's noticeably slower. (Easiest way to compare is to run the same keyword query on this local build and the site online, which is the same but without full-text search patched into 

Thoughts, anyone? @mscuthbert? Would appreciate some other-than-me user testing before we decide whether to patch this in or not.

### CODE REVIEW

**Comment by ryaanahmed** [comment]
If we're happy to be locked in to postgres, which I think that at this point we are, we can speed this up probably quite a lot by using some postgres-backend only features in Django: https://docs.djangoproject.com/en/2.1/ref/contrib/postgres/search/

**Comment by srisi** [comment]
Could you implement the postgres search vectors in such a way that it is still compatible with sqlite? i.e. if db == postgres, store and search text using postgres fts table, else store and search as a normal text field?
If we want to generalize the project down the road, we can't expect people to have a postgres server running but sqlite should be available.

**Comment by ryaanahmed** [comment]
> Could you implement the postgres search vectors in such a way that it is still compatible with sqlite? i.e. if db == postgres, store and search text using postgres fts table, else store and search as a normal text field?

Possible, but my inclination is to optimize for speed now -- which means making our code less general -- and then to generalize again when we fork this into a template project for others.

**Comment by ryaanahmed** [comment]
Did a few things for performance
- added the postgres-only SearchVectorField and an index for it --> running postgres locally, I go from ~1500 ms per search to ~300, so I am hopeful that this solves the speed issue
- added some other db indices

Not really related to this PR, but threw it in anyway
- pickled the data for the timeline view

**Pull request merged**
