### PR TITLE
changes to design

### PR DESCRIPTION
**Pull request by Mayowa99**
1) made the story titles link to the stories
2) changed the story boxes on the index page from card decks to flexible containers 
3) got rid of the extra sample stories
4) made the images on the story cards image containers

### CODE REVIEW

**Comment by ryaanahmed** [comment]
Definitely a step in the right direction! I'd ask for a few changes before we merge this in...

Screen Shot 2019-04-24 at 10 42 22 AM

1. Let's try vertically centering the story title h5 elements in the containing div. (See how "Beginnings of MIT" has space under it, since the containing divs are all the same size, but the text doesn't necessarily fit two lines?)

2. I'd suggest a bigger font size difference between the story title and the teaser.

3. Let's get the images to all be the same size, so that there's a better sense of alignment. You can set a max-height and then a height using vh (so that the images are a certain fixed percent of viewport height), then image-fit: contain, so that they letterbox or get framed correctly.

**Comment by ryaanahmed** [comment]
Taking a look around at some similar design patterns...

Victoria and Albert Museum
Screen Shot 2019-04-24 at 10 48 38 AM

@srisi 's tobacco analytics site
Screen Shot 2019-04-24 at 10 50 35 AM

our site!
Screen Shot 2019-04-24 at 10 48 20 AM

Boston Children's Museum has a cool pattern -- when you mouse over the titles, you get a teaser (try visiting the site https://www.bostonchildrensmuseum.org/)
Screen Shot 2019-04-24 at 10 54 36 AM

**Comment by ryaanahmed** [comment]
My instinct is to move the title back underneath the image, since the titles are not of consistent length, but we can coerce the images to all be the same size. This would make it look a little more tidy and regular.

**Comment by Mayowa99** [comment]
I agree that it definetly looks better under the image, should I still center the titles? I'm thinking that with this set up it would be better not to.

**Comment by Mayowa99** [comment]
I'm curious as to how you got the three stories to rotate with the different reloads. Also, other than the stories, what else do we want to put on the homepage? the network analysis maybe?

**Comment by mscuthbert** [comment]
I'll put a short explanation of what the project is like we have for gender novels.  I think that everything else we should make a very short story linking to the page itself.  For instance, the network analysis can have its explanation in a story, etc.

**Comment by ryaanahmed** [comment]
@Mayowa99 — I agree, I think it looks better without centering the titles. Check out what's going on in apps.archives.views.index to see how the rotating random stories work.

@mscuthbert—I think that's a good idea. Maybe let's permalink the network visualization in the middle, and randomly select two other stories?

What about having a big search bar front and center on the homepage?

**Pull request merged**
